CREATE TABLE EMPLOYEE (
    ID VARCHAR(255) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    MIDDLE_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    GENDER VARCHAR(255),
    BIRTH_DATE DATE,
    DATE_CREATED TIMESTAMP,
    DATE_LAST_UPDATED TIMESTAMP
);
